#!/bin/bash


NAME=ReceptionAssistant_Python_Persona
DIR=/var/www/ReceptionAssistant_Python
USER=root
GROUP=root
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/env/bin/activate
# BIND=unix:$DIR/run/gunicorn.sock
BIND=0.0.0.0:8100
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn personaMain:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
